<a href="https://colab.research.google.com/github/gKorada/PythonNotebooks/blob/main/Car_Recommender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [46]:
pip install ucimlrepo

Requirement already satisfied: ucimlrepo in /usr/local/lib/python3.11/dist-packages (0.0.7)
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from ucimlrepo) (2.2.2)
Requirement already satisfied: certifi>=2020.12.5 in /usr/local/lib/python3.11/dist-packages (from ucimlrepo) (2025.8.3)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)

In [47]:
import pandas as pd

In [48]:
from ucimlrepo import fetch_ucirepo

# fetch dataset
auto_mpg = fetch_ucirepo(id=9)

# data (as pandas dataframes)
X = auto_mpg.data.features
y = auto_mpg.data.targets
z = auto_mpg.names
# metadata
print(auto_mpg.metadata)

# variable information
print(auto_mpg.variables)

{'uci_id': 9, 'name': 'Auto MPG', 'repository_url': 'https://archive.ics.uci.edu/dataset/9/auto+mpg', 'data_url': 'https://archive.ics.uci.edu/static/public/9/data.csv', 'abstract': 'Revised from CMU StatLib library, data concerns city-cycle fuel consumption', 'area': 'Other', 'tasks': ['Regression'], 'characteristics': ['Multivariate'], 'num_instances': 398, 'num_features': 7, 'feature_types': ['Real', 'Categorical', 'Integer'], 'demographics': [], 'target_col': ['mpg'], 'index_col': ['car_name'], 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 1993, 'last_updated': 'Thu Aug 10 2023', 'dataset_doi': '10.24432/C5859H', 'creators': ['R. Quinlan'], 'intro_paper': None, 'additional_info': {'summary': 'This dataset is a slightly modified version of the dataset provided in the StatLib library.  In line with the use by Ross Quinlan (1993) in predicting the attribute "mpg", 8 of the original instances were removed because they had unknown values for the "mpg" attribute.  The original dataset is available in the file "auto-mpg.data-original".\r\n\r\n"The data concerns city-cycle fuel consumption in miles per gallon, to be predicted in terms of 3 multivalued discrete and 5 continuous attributes." (Quinlan, 1993)', 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': '    1. mpg:           continuous\r\n    2. cylinders:     multi-valued discrete\r\n    3. displacement:  continuous\r\n    4. horsepower:    continuous\r\n    5. weight:        continuous\r\n    6. acceleration:  continuous\r\n    7. model year:    multi-valued discrete\r\n    8. origin:        multi-valued discrete\r\n    9. car name:      string (unique for each instance)', 'citation': None}}
           name     role         type demographic description units  \
0  displacement  Feature   Continuous        None        None  None
1           mpg   Target   Continuous        None        None  None
2     cylinders  Feature      Integer        None        None  None
3    horsepower  Feature   Continuous        None        None  None
4        weight  Feature   Continuous        None        None  None
5  acceleration  Feature   Continuous        None        None  None
6    model_year  Feature      Integer        None        None  None
7        origin  Feature      Integer        None        None  None
8      car_name       ID  Categorical        None        None  None

  missing_values
0             no
1             no
2             no
3            yes
4             no
5             no
6             no
7             no
8             no

Data Cleaning

In [49]:
column_names = [
    'mpg', 'cylinders', 'displacement', 'horsepower',
    'weight', 'acceleration', 'model_year', 'origin', 'car_name'
]

car_df = pd.read_csv('/content/drive/MyDrive/auto-mpg.data', delim_whitespace=True, header=None, names=column_names, na_values='?')

car_df.head()

/tmp/ipython-input-3371358629.py:6: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  car_df = pd.read_csv('/content/drive/MyDrive/auto-mpg.data', delim_whitespace=True, header=None, names=column_names, na_values='?')

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,car_name
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150.0,3433.0,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140.0,3449.0,10.5,70,1,ford torino

In [50]:
car_df = pd.read_csv('/content/drive/MyDrive/Ad_table.csv')
car_copy = car_df
car_copy.head()

/tmp/ipython-input-3726710648.py:1: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  car_df = pd.read_csv('/content/drive/MyDrive/Ad_table.csv')

,Maker,Genmodel,Genmodel_ID,Adv_ID,Adv_year,Adv_month,Color,Reg_year,Bodytype,Runned_Miles,Engin_size,Gearbox,Fuel_type,Price,Seat_num,Door_num
0,Bentley,Arnage,10_1,10_1$$1,2018,4,Silver,2000.0,Saloon,60000,6.8L,Automatic,Petrol,21500,5.0,4.0
1,Bentley,Arnage,10_1,10_1$$2,2018,6,Grey,2002.0,Saloon,44000,6.8L,Automatic,Petrol,28750,5.0,4.0
2,Bentley,Arnage,10_1,10_1$$3,2017,11,Blue,2002.0,Saloon,55000,6.8L,Automatic,Petrol,29999,5.0,4.0
3,Bentley,Arnage,10_1,10_1$$4,2018,4,Green,2003.0,Saloon,14000,6.8L,Automatic,Petrol,34948,5.0,4.0
4,Bentley,Arnage,10_1,10_1$$5,2017,11,Grey,2003.0,Saloon,61652,6.8L,Automatic,Petrol,26555,5.0,4.0

In [51]:
car_copy = car_copy.drop(columns=['Genmodel_ID', 'Adv_ID', 'Adv_month', 'Engin_size','Seat_num', 'Door_num', 'Color'])

car_copy.head()

,Maker,Genmodel,Adv_year,Reg_year,Bodytype,Runned_Miles,Gearbox,Fuel_type,Price
0,Bentley,Arnage,2018,2000.0,Saloon,60000,Automatic,Petrol,21500
1,Bentley,Arnage,2018,2002.0,Saloon,44000,Automatic,Petrol,28750
2,Bentley,Arnage,2017,2002.0,Saloon,55000,Automatic,Petrol,29999
3,Bentley,Arnage,2018,2003.0,Saloon,14000,Automatic,Petrol,34948
4,Bentley,Arnage,2017,2003.0,Saloon,61652,Automatic,Petrol,26555

In [52]:
car_copy.drop(columns = ['Gearbox'], inplace = True)
car_copy.head()

     Maker Genmodel  Adv_year  Reg_year Bodytype Runned_Miles Fuel_type  Price
0  Bentley   Arnage      2018    2000.0   Saloon        60000    Petrol  21500
1  Bentley   Arnage      2018    2002.0   Saloon        44000    Petrol  28750
2  Bentley   Arnage      2017    2002.0   Saloon        55000    Petrol  29999
3  Bentley   Arnage      2018    2003.0   Saloon        14000    Petrol  34948
4  Bentley   Arnage      2017    2003.0   Saloon        61652    Petrol  26555

In [53]:
car_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 268255 entries, 0 to 268254
Data columns (total 8 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Maker         268255 non-null  object
 1   Genmodel      268255 non-null  object
 2   Adv_year      268255 non-null  int64
 3   Reg_year      268248 non-null  float64
 4   Bodytype      267301 non-null  object
 5   Runned_Miles  267200 non-null  object
 6   Fuel_type     267846 non-null  object
 7   Price         268255 non-null  object
dtypes: float64(1), int64(1), object(6)
memory usage: 16.4+ MB

In [54]:
car_copy['Runned_Miles'].isna().sum()

np.int64(1055)

In [55]:
car_copy['Price'].isna().sum()

np.int64(0)

In [62]:
car_copy.dropna(inplace = True)

car_copy.isna().sum()

Maker           0
Genmodel        0
Adv_year        0
Reg_year        0
Bodytype        0
Runned_Miles    0
Fuel_type       0
Price           0
dtype: int64

In [64]:
car_copy['Runned_Miles']

0          60000
1          44000
2          55000
3          14000
4          61652
           ...
268249    107000
268250      1800
268252         6
268253      1538
268254       500
Name: Runned_Miles, Length: 265940, dtype: object

In [63]:
car_copy['Runned_Miles'] = car_copy['Runned_Miles'].astype(int)
car_copy['Price'] = car_copy['Price'].astype(int)

ValueError: invalid literal for int() with base 10: '1 mile'

So I was thinking creating some type of score based on runned miles, price and body type. The runned miles score would be if the car model avg runned miles is a certain number, attribute a score of 1-5 from it. Same concept for the price. Body Type I have no idea honestly, might just use it to help the alogrithim pick based on the user's choice.

Miles score first

In [ ]:
car_avg = car_copy.groupby('Runned_Miles').mean()
car_avg.head()